name = "SciMLLogging"
uuid = "a6db7da4-7206-11f0-1eab-35f2a5dbe1d1"
authors = ["Jadon Clugston"]
version = "1.1.0"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"

[compat]
DocStringExtensions = "0.9.5"
Logging = "1.1.0"
LoggingExtras = "1.1.0"
Preferences = "1.5.0"
SafeTestsets = "0.1.0"
julia = "1.10"

[extras]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets", "DocStringExtensions"]
