name = "SciMLVerbosity"
uuid = "a05b3ec9-34a1-438a-b0a1-c0adb433119f"
authors = ["Jadon Clugston"]
version = "1.0.0-DEV"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Moshi = "2e0e35c7-a2e4-4343-998d-7ef72827ed2d"

[compat]
DocStringExtensions = "0.9.5"
Moshi = "0.3.6"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
