name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  tests:
    name: "Tests"
    strategy:
      fail-fast: true
      matrix:
        version:
          - '1'
          - 'lts'
          - 'pre'
        group:
          - Core
        include:
          - version: '1'
            group: NoPre
          - version: 'lts'
            group: NoPre
          - version: '1'
            group: Downstream
    uses: "SciML/.github/.github/workflows/tests.yml@v1"
    with:
      julia-version: "${{ matrix.version }}"
      group: "${{ matrix.group }}"
      coverage: false
    secrets: "inherit"
