name: Downgrade
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
jobs:
  downgrade:
    strategy:
      fail-fast: false
      matrix:
        version: ['1.10']
    uses: "SciML/.github/.github/workflows/downgrade.yml@v1"
    with:
      julia-version: "${{ matrix.version }}"
      skip: "Pkg,TOML"
    secrets: "inherit"
