name: IntegrationTest
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:

jobs:
  test:
    name: ${{ matrix.package.repo }}/${{ matrix.package.group }}
    strategy:
      fail-fast: false
      matrix:
        package:
          - {user: SciML, repo: LinearSolve.jl, group: All}
          - {user: SciML, repo: NonlinearSolve.jl, group: Core}
          - {user: SciML, repo: OrdinaryDiffEq.jl, subdir: lib/DiffEqBase, group: Core}
          - {user: SciML, repo: OrdinaryDiffEq.jl, subdir: lib/DiffEqBase, group: Downstream}
          - {user: SciML, repo: OrdinaryDiffEq.jl, subdir: lib/DiffEqBase, group: Downstream2}
          - {user: SciML, repo: OrdinaryDiffEq.jl, group: Interface}
          - {user: SciML, repo: OrdinaryDiffEq.jl, group: Integrators}
          - {user: SciML, repo: OrdinaryDiffEq.jl, group: Regression}
    uses: "SciML/.github/.github/workflows/downstream.yml@v1"
    with:
      owner: "${{ matrix.package.user }}"
      repo: "${{ matrix.package.repo }}"
      subdir: "${{ matrix.package.subdir }}"
      group: "${{ matrix.package.group }}"
      julia-version: "1"
    secrets: "inherit"
